/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Commission {
  'id' : bigint,
  'status' : string,
  'partnerPrincipal' : Principal,
  'paymentDate' : [] | [bigint],
  'amount' : bigint,
}
export interface Lead {
  'id' : bigint,
  'customerName' : string,
  'status' : LeadStatus,
  'partnerPrincipal' : Principal,
}
export type LeadStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'contacted' : null } |
  { 'inProgress' : null };
export interface Partner {
  'principal' : Principal,
  'name' : string,
  'licenseInfo' : string,
  'companyName' : string,
  'contactDetails' : string,
}
export interface Property {
  'id' : bigint,
  'status' : string,
  'propertyType' : string,
  'price' : bigint,
  'location' : string,
}
export interface UserProfile {
  'name' : string,
  'licenseInfo' : string,
  'companyName' : string,
  'contactDetails' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommission' : ActorMethod<[Principal, bigint, string], undefined>,
  'addLead' : ActorMethod<[string], undefined>,
  'addProperty' : ActorMethod<[string, bigint, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommissions' : ActorMethod<[], Array<Commission>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getPartnerProfile' : ActorMethod<[], [] | [Partner]>,
  'getProperties' : ActorMethod<[], Array<Property>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markCommissionPaid' : ActorMethod<[bigint, bigint], undefined>,
  'registerPartner' : ActorMethod<[string, string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];