/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'licenseInfo' : IDL.Text,
  'companyName' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const Commission = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'partnerPrincipal' : IDL.Principal,
  'paymentDate' : IDL.Opt(IDL.Int),
  'amount' : IDL.Nat,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'contacted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : LeadStatus,
  'partnerPrincipal' : IDL.Principal,
});
export const Partner = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'licenseInfo' : IDL.Text,
  'companyName' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'propertyType' : IDL.Text,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommission' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'addLead' : IDL.Func([IDL.Text], [], []),
  'addProperty' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommissions' : IDL.Func([], [IDL.Vec(Commission)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getPartnerProfile' : IDL.Func([], [IDL.Opt(Partner)], ['query']),
  'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markCommissionPaid' : IDL.Func([IDL.Nat, IDL.Int], [], []),
  'registerPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'licenseInfo' : IDL.Text,
    'companyName' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const Commission = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'partnerPrincipal' : IDL.Principal,
    'paymentDate' : IDL.Opt(IDL.Int),
    'amount' : IDL.Nat,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'contacted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : LeadStatus,
    'partnerPrincipal' : IDL.Principal,
  });
  const Partner = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'licenseInfo' : IDL.Text,
    'companyName' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'propertyType' : IDL.Text,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommission' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'addLead' : IDL.Func([IDL.Text], [], []),
    'addProperty' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommissions' : IDL.Func([], [IDL.Vec(Commission)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getPartnerProfile' : IDL.Func([], [IDL.Opt(Partner)], ['query']),
    'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markCommissionPaid' : IDL.Func([IDL.Nat, IDL.Int], [], []),
    'registerPartner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };